#ifndef _INCLUDED_ring_neurons_spike_thresholder_codeobject_2_after
#define _INCLUDED_ring_neurons_spike_thresholder_codeobject_2_after

void _after_run_ring_neurons_spike_thresholder_codeobject_2();

#endif
