#ifndef _INCLUDED_ring_synapses_asym_pre_codeobject_2
#define _INCLUDED_ring_synapses_asym_pre_codeobject_2

void _run_ring_synapses_asym_pre_codeobject_2();

void _debugmsg_ring_synapses_asym_pre_codeobject_2();

#endif
