#ifndef _INCLUDED_ring_synapses_asym_pre_codeobject_3
#define _INCLUDED_ring_synapses_asym_pre_codeobject_3

void _run_ring_synapses_asym_pre_codeobject_3();

void _debugmsg_ring_synapses_asym_pre_codeobject_3();

#endif
